import type { Metadata } from 'next';

import './globals.css';

import { HomeLayout } from '@/components/layout';

import ThemeProviderContext from '@/utils/context/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body>
        <ThemeProviderContext>
          <HomeLayout>{children}</HomeLayout>
        </ThemeProviderContext>
      </body>
    </html>
  );
}
